FROM node:20-bullseye-slim
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY angular.json tsconfig.json tsconfig.app.json tsconfig.spec.json ./
EXPOSE 4200
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]
